[package]
authors = ["Christian Schilling <christian.schilling@esrlabs.com>"]
description = "GIT virtualization proxy"
edition = "2018"
keywords = ["git", "monorepo", "workflow", "scm"]
license-file = "LICENSE"
name = "josh-proxy"
readme = "README.md"
repository = "https://github.com/esrlabs/josh"
version = "0.3.0"

[dependencies]
bincode = "*"
clap = "2"
futures = "0.3"
futures-cpupool = "0.1"
git2 = {version = "*", default-features = false}
hyper = "0.11"
#hyper-tls = "0.1"
#hyper-fs = "*"
josh = {path = "../"}
josh-review = {path = "../josh-review"}
lazy_static = "1.4"
log = "0.4"
rand= "0.7"
regex = "1.4"
reqwest= {version = "0.9", default-features = false}
ring = "*"
rs_tracing= { version = "1.0", features = ["rs_tracing"]}
rust-crypto = "0.2"
serde = "*"
serde_json= "1.0"
structopt = "0.3"
tempfile = "*"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-process = "0.2"
toml = "*"
base64 = "*"
tracing = { version = "*", features = ["max_level_debug", "release_max_level_info"] }
tracing-futures = "*"
tracing-log = "*"
tracing-subscriber = "0.2.15"
uuid = {version = "0.8", features = ["v4"]}
