
[package]
authors = ["Christian Schilling <christian.schilling@esrlabs.com>"]
description = "GIT virtualization proxy"
edition = "2018"
keywords = ["git", "monorepo", "workflow", "scm"]
license-file = "LICENSE"
name = "josh-proxy2"
readme = "README.md"
repository = "https://github.com/esrlabs/josh"
version = "0.3.0"


[dependencies]
clap = "2"
futures = "0.3"
tokio = {version = "0.2", features = ["full"] }
hyper = "0.13"
hyper_cgi = {version = "0.1"}
toml = "*"
git2 = {version = "*", default-features = false}
tracing = { version = "*", features = ["max_level_debug", "release_max_level_info"] }
tracing-futures = "*"
tracing-subscriber = "*"
reqwest= {version = "0.10", default-features = false, features = ["blocking", "json"]}
uuid = {version = "0.8", features = ["v4"]}
base64 = "0.12"
regex = "1.4"
lazy_static = "1.4"
josh = {path = "../"}
serde_json= "1.0"
rust-crypto = "0.2"
