[package]
name = "josh"
version = "0.3.0"
repository = "https://github.com/esrlabs/josh"
authors = ["Christian Schilling <christian.schilling@esrlabs.com>"]
license-file = "LICENSE"
description = "GIT virtualization proxy"
keywords = ["git", "monorepo", "workflow", "scm"]
readme = "README.md"
edition = "2018"

[workspace]
members = ["josh-proxy", "josh-review"]

[dependencies]
git2 = {version = "0.13", default-features = false}
clap = "2"
tracing = { version = "*", features = ["max_level_debug", "release_max_level_info"] }
bincode = "*"
percent-encoding = "2.1"
serde = {version = "*", features = ["derive"]}
atomicwrites = "*"
regex = "1.4"
lazy_static = "1.4"
pest_derive = "2.1"
pest= "2.1"
serde_json= "1.0"
rs_tracing= { version = "1", features = ["rs_tracing"]}
tracing-log = "*"
tracing-subscriber = "0.2.15"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

